# Generated by Django 3.1.3 on 2020-12-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='car',
            new_name='equipment',
        ),
    ]
